### ISSUE TITLE
Cannot install plugins from secure registry, it requires npm login(not working with global npm)

### ISSUE THREAD

**Issue by nurra01** [zowe/imperative#111]
If I want to install plugins from secure registry need to login first using "username", "password" and "email". If user doesn't have npm he is not able to install from secure registries.

**Comment by nurra01** [comment]
The solution could be adding these options to install and update commands so it logins with passed credentials and then install from secure registry. It would like smth lihe this:
install plugins "plugin-name" --registry "registry-name" --username  "user" --password "pass" --email "mail"

**Comment by AHumanFromCA** [comment]
What if we were to only add 1 flag `--login` or even a command `registry-login` that just did:

```typescript
execSync(`"${process.execPath}" "/node_modules/npm" login`, {stdio: [0,1,2]});
```

This would execute the underlying command, which prompts the user for these fields. The benefit we get out of this is the password can be hidden from the console (based on how npm is doing it). This method also doesn't prevent a script from executing the login, an example on how this is done can be seen here:

https://github.com/zowe/imperative/blob/88b829ce6412f30afee28064108713c63033ebf5/Jenkinsfile#L601-L605
https://github.com/zowe/imperative/blob/88b829ce6412f30afee28064108713c63033ebf5/jenkins/npm_login.expect#L1-L23

**Comment by AHumanFromCA** [comment]
If we did create the `registry` group we could also create commands for `set` and `set-scope` to allow for configuration of `npm config set registry` and `npm config set @scope:registry`

This would probably require us to refacto the entire plugin group to have each command be arbitrarily 4 levels deep instead of the current 3 so that each level is consistent. That would take care of #39 as well.

**Comment by nurra01** [comment]
@AHumanFromCA I like command creating command group option more. I would create enhancement for it.
