### ISSUE TITLE
Config group for CLIs

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/imperative#126]
### Overview
Imperative should provide a configuration group to manage settings of a CLI.

For example,

In PR #30, we introduced the concept of a plugin providing a credential manager. Currently to enable this, a user must go into the cli home directory and add the name of the plugin in the settings.json file. The settings file looks something like this:

```JSON
{
  "overrides": {
    "CredentialManager": "name-of-your-plugin | false"
  }
}
```

Changing this may not be intuitive to users. Also, once this value is changed, profile contents stored using the previous mechanism become inaccessible. This is where the config group can be of use.

### What I am proposing

A config group that has the ability to set values in the settings.json.

The following commands:

#### SET
Set a value in the configuration.

```
cli config set credential-manager name-of-plugin
```

#### GET
Get the value of a configuration or show all the configuration.

```
cli config get <all | credential-manager>
```

#### RESET
Reset the value of a configuration or reset all values to default

```
cli config reset <all | credential-manager>
```

When setting a credential manager, the group could also work on transferring the credentials from the old manager to the new manager. This opens up the possibility for a plugin to properly set the credential manager on postinstall/preuninstall.

**Comment by jelaplan** [comment]
This story proposes creating a configuration group for Imperative. But, the use case is to use that for Secure Credential Store. Do we see the configuration group being needed more widely. If not, I wonder if we could create a Secure Credential Store group in Imperative or in the Secure Credential Store plug-in? I think it a separate group, named in a generic way will be an impediment to people understanding how to use these capabilities.

**Comment by AHumanFromCA** [comment]
Hi @jelaplan,

The simple answer is yes, other things would take advantage of this.

Some things that will:
- Anything planned in the future that could be overridden by a plugin. An immediate thing would be #118 

Some things that could:
- Logging levels present in the application. Currently these are loaded in an environment variable and the user has to make sure they type the string correctly. A group could be created to help them set the
level to specific values reducing the possibility of them setting an invalid log level when requested by someone supporting them.
- Log file count
- log file size

There are probably more things, that could be in this group but I just named a few.

Also, most CLIs that have complex settings also have a config group. I would think that we should stick to the standard for such configuration as a separate group not named config would probably cause more confusion to the average cli user...but again I'm not a UX engineer so I might be making assumptions that aren't valid.

**Comment by jelaplan** [comment]
@AHumanFromCA Is there a story proposing to add the additional things like logging level? Seems worthy because then poeple have an in-tool way to set those things.

**Comment by AHumanFromCA** [comment]
Hi @jelaplan,

I could not answer this question with any accuracy since I no longer work on this project. Perhaps @zFernand0 or @MikeBauerCA could help you out.

**Comment by t1m0thyj** [comment]
This config group was implemented in Zowe v1, and is planned to be deprecated in Zowe v2.
