### ISSUE TITLE
Allow re-naming of profiles through the CLI 

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/imperative#13]
It would be convenient for users to be able to rename existing profiles via the auto-generated profile commands e.g. 

```
$ my-cli profiles rename banana  banana1 banana2
  Profile 'banana1' of type 'banana' has been succesfully renamed to 'banana2'. 
```

**Comment by t1m0thyj** [comment]
Enhancements to the "zowe profiles" group are no longer being considered since it is deprecated in Zowe v2.
