### ISSUE TITLE
Unit test failures with strange "random" path changes

### ISSUE THREAD

**Issue by tucker01** [zowe/imperative#136]
When running unit tests on Jenkins or local PC test will intermittently fail with changes to paths and slashes. It is seemingly random. Rerunning tests or replaying builds may pass. Witnessed in rest client tests, plugin management tests, among others. 
```
- Snapshot
+ Received
@@ -2,9 +2,9 @@
"headers": Object {
"Content-Type": "application/json",
},
"hostname": "test",
"method": "GET",
- "path": "/resource",
+ "path": "///resource",
"port": 443,
"rejectUnauthorized": true,
}
```

**Comment by gejohnston** [comment]
The unit tests no longer produce these errors.
