### ISSUE TITLE
Deprecation warnings on keytar/node_report install

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/imperative#18]
Issue
----------------
Just recently upgraded to NodeJS 10 and performed a fresh local install of the brightside project. This fresh install had multiple warnings in the post install setup of keytar and node_report.

This is just one of the many messages that I got:

```
C:\Users\xxxxxxx\Documents\GitHub\brightside\node_modules\nan\nan.h(869): warning C4996: 'no de::MakeCallback': was declared deprecated (compiling source file ..\src\node_report.cc) [C: \Users\xxxxxxx\Documents\GitHub\brightside\node_modules\node-report\build\api.vcxproj]
  C:\Users\xxxxxxx\.node-gyp\10.6.0\include\node\node.h(163): note: see declaration of 'node
  ::MakeCallback' (compiling source file ..\src\node_report.cc)
```
```
..\src\main.cc(18): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declared deprecated
C:\Users\xxxxxxxxx\Documents\GitHub\brightside\node_modules\keytar\build\keytar.vcxproj]
```

Not sure if there is a fix yet, but it is something that should be addressed.

Environment
----------------

| Name | Version |
|--------|----------|
| NodeJS | 10.6.0 |
| npm | 6.0.0 |

**Comment by t1m0thyj** [comment]
No longer applicable since Node.js 10 has reached End of Life.
