### ISSUE TITLE
Allow handlers to set process exit code when throwing an error

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/imperative#187]
Ways to implement: 

In Imperative.ts:562

```
  definer.define(child,
                (args: Arguments, response: IYargsResponse) => {
                    if (!response.success) {
                        process.exitCode = Constants.ERROR_EXIT_CODE;
                    }
                }, commandResponseParms
            );
```
A:
We could avoid setting process.exitCode if it has already been set to something else. Like: 
` if (!response.success && process.exitCode == null) `

B:
We could add a new field to IImperativeError for exit code and check if that has been set. 

I kind of prefer A for allowing the natural way to set exit code in Node

**Comment by ChrisBoehmCA** [comment]
@tucker01  have a preference for how to implement?

**Comment by tucker01** [comment]
Another option is to allow the set of the exit code in the "response" object. We could also set the status code then in the JSON response?
