### ISSUE TITLE
When generating Markdown from command help, # is not escaped

### ISSUE THREAD

**Issue by matthewpwilson** [zowe/imperative#202]
If I put a '#' character in my command's description, when the Markdown doc is generated this is not escaped. So it's interpreted as a heading. 

For example by including the following line in my description:
```
Upload a local directory to a USS directory.\n\n
An optional .zosattributes file in the source directory can be used to control file conversion and tagging.\n\n
An example .zosattributes file: \n
# pattern        local-encoding        remote-encoding
```
the generated Markdown looks like this:
### dir-to-uss<a name="command-dir-to-uss"></a>
Upload a local directory to a USS directory.

An optional .zosattributes file in the source directory can be used to control
file conversion and tagging.

An example .zosattributes file:
# pattern local-encoding remote-encoding

**Comment by ChrisBoehmCA** [comment]
Good catch. Sorry for the issues with the markdown generation. You guys are giving it a run for its money haha.
