### ISSUE TITLE
Unexpected prompting error: 'prepared.args[option.name][0].toUpperCase is not a function'

### ISSUE THREAD

**Issue by PeteSwauger** [zowe/imperative#216]
Prompting code causes an error when a parameter is numeric by trying to use the string 'toUpperCase function.  Even if the parameter is entered as a string yargs converts it to numeric.

**Comment by zFernand0** [comment]
Not sure if this is still an issue.
For reference:
https://github.com/zowe/imperative/blob/26bb8c0e1ff703eb5365d14de13859398614153b/packages/cmd/src/CommandProcessor.ts#L421
https://github.com/zowe/imperative/blob/26bb8c0e1ff703eb5365d14de13859398614153b/packages/cmd/src/CommandProcessor.ts#L464

**Comment by gejohnston** [comment]
Current code determines that prepared.args[option.name] is a string before attempting to use the toUpperCase function. No consumer issues have been opened to indicate that the current code demonstrates such a problem. Closing this issue.
