### ISSUE TITLE
Need access to response headers from RestClient

### ISSUE THREAD

**Issue by paulscott-psi** [zowe/imperative#243]
Since the REST API response Content-Type may be any one of the types specified in an Accept request header, the client needs to check the Content-Type response header to understand the format of the returned response.  Currently, the RestClient does not seem to surface the response headers.

**Comment by dkelosky** [comment]
Hi @paulscott-psi - It is possible to obtain header information from the RestClient via something like this:
```typescript
import { RestClient, Session } from "@zowe/imperative";

const session = new Session({
    hostname: "jsonplaceholder.typicode.com",
    port: 443,
});

(async () => {
    const client = new RestClient(session);
    const data = await client.performRest("posts", "GET");
    console.log(client.response.headers['content-type'])
})();
```

This test prints a response: `application/json; charset=utf-8`.  

it seems like this could be made a little more user-friendly with a helper API - will this be an OK workaround for you in the meantime? 

Thanks,

**Comment by paulscott-psi** [comment]
My colleague and I agree this provides what is needed. Thanks!
