### ISSUE TITLE
Some web help was lost in a recent push to the HelpBrowser branch

### ISSUE THREAD

**Issue by gejohnston** [zowe/imperative#245]
Details that were available in web help were lost in an update pushed into the HelpBrowser branch.

By testing various snapshots, I believe that the change was introduced in one of the following commits.
- Fix web help tree sometimes not expanding to full height
    Commit hash:	574c5bb5c0f9906a924b75383229ed9fa6e180cb
- Add missing header tag for web help tree
    Commit hash:	4adda65952b604362cb5bfc76eb3cc8324609c49

Without those commits, the good help looks like this:
    
![original_good_help](https://user-images.githubusercontent.com/37119146/60303889-a7c36f00-9905-11e9-8824-6345f1d0c6bc.png)

With those commits, the lost help looks like this:
![lost_help](https://user-images.githubusercontent.com/37119146/60303921-c6296a80-9905-11e9-9085-8ebaceda45ee.png)

Every page displays a similar behavior.

**Comment by gejohnston** [comment]
Further investigation by Timothy, identified the following:
- When a different version of imperative is rebuilt, the webhelp directory must be deleted (which causes the webhelp to be re-generated). The correct help is then displayed.

I do not believe that this situation will occur at a customer site. Any end-user upgrade-install of Zowe-cli will change the product version number which should trigger a re-generation of the WebHelp. I will leave this issue around for a few days to see if anyone else sees a flaw in this thinking, and then probably just close this issue.

**Comment by tjohnsonBCM** [comment]
> I do not believe that this situation will occur at a customer site. Any end-user upgrade-install of Zowe-cli will change the product version number which should trigger a re-generation of the WebHelp. I will leave this issue around for a few days to see if anyone else sees a flaw in this thinking, and then probably just close this issue.

I agree this logic seems sound. The problem in this case was that the file `main.css` (the primary stylesheet that controls the layout of web help and is bundled with Imperative) had breaking changes made to it, which required web help to be regenerated to make `index.html` (the main web help page which Imperative generates on demand) compatible with the latest CSS.

As long as we change the product version number any time we make breaking changes to the CSS/JS files used by web help, then regeneration of the web help should automatically be triggered. Therefore, customers should never experience this situation.

**Comment by gejohnston** [comment]
Since no objections have been raised, I am closing this issue as it is a non-problem.
