### ISSUE TITLE
Tests not able to find "imperative-test-cli" causing failures. 

### ISSUE THREAD

**Issue by tucker01** [zowe/imperative#252]
I ran

```
npm install --@zowe:registry=https://registry.npmjs.org --no-package-lock --force
npm run build
```

Then I ran 

` npm run test:unit -- -u && npm run test:integration -- -u`

See attached log for results of this last command;

[test.log](https://github.com/zowe/imperative/files/3380453/test.log)

**Comment by tucker01** [comment]
@paulscott-psi Since they are installed globally, as a sanity check, can you try: 
```
imperative-test-cli
```
To see if it displays the help. The test tasks will uninstall them after the tests, but it looks like it failed before that point.

**Comment by paulscott-psi** [comment]
Not sure how you wanted that run. I ran:

`npm run test:integration imperative-test-cli`

[imperative-test-cli.log](https://github.com/zowe/imperative/files/3382943/imperative-test-cli.log)

**Comment by tucker01** [comment]
Oh sorry, I mean't just try issuing the bin right at your terminal:
```
imperative-test-cli
```

**Comment by paulscott-psi** [comment]
Oh, sorry, I should have told you I did that, but it didn't work. Which didn't surprise me since it's not in my PATH.

```
%imperative-test-cli
imperative-test-cli: Command not found.

```

So I ran it as an npm parameter.

**Comment by paulscott-psi** [comment]
Oh, and a "find" in my local repository didn't find any such file ... only a directory of that name.

**Comment by tucker01** [comment]
Is the path specified by `npm config get prefix` in your path?

**Comment by paulscott-psi** [comment]
No.

%npm config get prefix
/Users/pscott/bin/node-v10.16.0

%ls ~/bin/node-v10.16.0/
CHANGELOG.md    LICENSE         README.md       bin/            include/        lib/            share/

%setenv | egrep PATH
PATH=/Users/pscott/bin:/Users/pscott/perl5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

%ls -la ~/bin/npm
lrwxrwxr-x  1 pscott  staff  21 Jun 18 21:29 /Users/pscott/bin/npm@ -> node-v10.16.0/bin/npm

pscott@Pauls-5K-iMac ~/<2>imperative %ls -la ~/bin/node
lrwxrwxr-x  1 pscott  staff  22 Jun 18 21:29 /Users/pscott/bin/node@ -> node-v10.16.0/bin/node

**Comment by tucker01** [comment]
Ok, that makes sense then. 

Globally installed packages are placed by npm in the directory specified by the npm prefix (`npm config get prefix` ... in your case: `/Users/pscott/bin/node-v10.16.0`)

You would need to place `/Users/pscott/bin/node-v10.16.0/bin` in your path to be able to execute globally installed packages that are CLIs (the reason the tests appear to be failing in the last output you had linked).

**Comment by paulscott-psi** [comment]
How can that be? That directory has no executables.

**Comment by tucker01** [comment]
I'm not exactly sure what npm does on macos, but it's probably pretty similar to linux:

![image](https://user-images.githubusercontent.com/37446232/61238413-956d7180-a70a-11e9-84e3-bf6958bc5c08.png)

Those are just links to the main javascript files (with the `#!/usr/bin/env node` shabang)

**Comment by paulscott-psi** [comment]
Ah, I see what you're referring to. I misread the path. I've added ~/bin/node-v10.16.0/bin to my PATH and removed the node, npm, and npx symbolic links since they're no longer required.

Now imperative-test-cli  runs. Also, here's the results of running commands previously requested:

`%npm install --@zowe:registry=https://registry.npmjs.org --no-package-lock --force`

[npm.install.log](https://github.com/zowe/imperative/files/3395430/npm.install.log)

`%npm run build`

[npm.run.build.log](https://github.com/zowe/imperative/files/3395433/npm.run.build.log)

`%npm run test:unit -- -u && npm run test:integration -- -u`

[npm.run.test.log](https://github.com/zowe/imperative/files/3395436/npm.run.test.log)

**Comment by tucker01** [comment]
Thanks. For the most part, it looks like the tests ran successfully, except for the keytar tests. Keytar is an npm package that allows imperative to store certain pieces of the profile in the operating systems credential vault. 

Keytar is reporting the error `User interaction is not allowed`. Let met get back to you on this one.
