### ISSUE TITLE
Unstable Pipeline For All Steps

### ISSUE THREAD

**Issue by dkelosky** [zowe/imperative#269]
Expanding individual steps in the Jenkins pipeline shows success, but the entire pipeline appears to show unstable (and makes it a little more difficult to determine which step actually failed):
![image](https://user-images.githubusercontent.com/14940561/63115366-03ed5b80-bf65-11e9-8a60-edc5c210e9b5.png)

**Comment by awharn** [comment]
This issue is no longer applicable because the project has migrated to GitHub Actions.
