### ISSUE TITLE
Keytar not Installed error masks actual error.

### ISSUE THREAD

**Issue by PeteSwauger** [zowe/imperative#27]
Receiving 'Keytar not Installed' error while debugging.  Set a breakpoint and discovered the actual error is due to keytar being compiled against an older version of Node.js. Actual error needs to be returned to the user.

The module '\\?\C:\Users\<user>\IdeaProjects\brightside\node_modules\keytar\build\Release\keytar.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by AHumanFromCA** [comment]
I think the main issue here comes down to these combination of lines:

https://github.com/zowe/imperative/blob/cf1325f652952c6abf638f452efcee7c1d3a0bc3/packages/security/src/DefaultCredentialManager.ts#L85-L94

https://github.com/zowe/imperative/blob/cf1325f652952c6abf638f452efcee7c1d3a0bc3/packages/cmd/src/profiles/CliProfileManager.ts#L216-L232

The load failure is put into causeErrors while all of the CliProfileManagers are outputting additional details. I think the quick fix is to add additionalDetails as `e.message` in the default manager source. Probably should wait until #21 is merged.

**Comment by zFernand0** [comment]
@t1m0thyj @awharn 
Should this issue be closed now that keytar is nodejs-version agnostic?

**Comment by t1m0thyj** [comment]
The cause of this error (Keytar failing to load because it was compiled for a different Node version) should no longer happen.

However, I suggest we keep this issue open because the "Keytar not Installed" message is still misleading in other cases. It really means "Keytar failed to load".

**Comment by t1m0thyj** [comment]
Error message updated to be more clear in vNext.
