### ISSUE TITLE
Session cannot be auto typecast-able to AbstractSession anymore

### ISSUE THREAD

**Issue by ChrisPark89** [zowe/imperative#285]
I get an error for this line:
`return ZosmfSession.createBasicZosmfSession(zosmfProfile);`

The error message is following:
```
Type 'Session' is not assignable to type 'AbstractSession'.
Types have separate declarations of a private property 'mISession'.ts(2322)
```

`ZosmfSession.createBasicZosmfSession()` This function returns `Session` type. And the caller function have to return `Promise<AbstractSession>` type.

This used to work, but not it's failing. Were there any changes on this?

**Comment by dkelosky** [comment]
I think it's related to this issue: https://github.com/zowe/zowe-cli/issues/512 

I think casting to `any` is the only work around until it's addressed.  Do you agree @tucker01 ?

**Comment by tucker01** [comment]
Sorry, missed this issue. We need to address this in a few areas, but for now, as long as versioning matches up... using `any` should be OK, but not ideal.

**Comment by matthewpwilson** [comment]
We've now hit this problem with 2.7.0 on @lts-incremental - is that expected? Seems like a breaking API change.

**Comment by tucker01** [comment]
We haven't had a chance to investigate yet. Sorry for the trouble. It shouldn't be causing a type error.

**Comment by asatklichov** [comment]
Hi,  today I also faced this issue, even our successful build started to give this error.  
e.g. tried versions: a) "4.15.0" b) "5.0.0-next.202107122104" 
And proposed workaround "any" is not solving that issue. Thank you

**Comment by zFernand0** [comment]
Seems like this is a pre-`zowe-v1-lts` method which no longer exists on `zowe-v2-lts`
Closing!
