### ISSUE TITLE
Can't install plugins from source on Linux

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/imperative#290]
Able to install plugin from source on Windows, but fails in Ubuntu 18.04 (attempted to install after executing `npm install` and `npm run build` for the plugin successfully):
![image](https://user-images.githubusercontent.com/50887074/65513001-5ac14b80-dea8-11e9-8816-74c15bb90faa.png)

**Comment by tjohnsonBCM** [comment]
Originally noticed this behavior for the CICS plugin, but @awharn tested and found it is an issue with other plugins as well. Therefore, moved this issue from the CICS plugin issue to here.

**Comment by awharn** [comment]
Further investigation suggests that it has something to do with imperative/packages/imperative/src/plugins/utilities/npm-interface/install.ts around line 94, specifically:

```
const regex = /\+\s(.*)@(.*)$/gm;
const match = regex.exec(installOutput);
const packageName = match[1];
let packageVersion = match[2];
```

When modified locally and the lines containing match[1] and match[2] were swapped, the error details changed to `Cannot read property '2' of null`. It seems that this snippet will return a valid match on Windows, but not on some Linux systems.

In this case, the installOutput was the following:
```
/home/andrew/.zowe/plugins/installed/lib
├── @zowe/cics-for-zowe-cli@3.0.0 
├── UNMET PEER DEPENDENCY @zowe/cli@^5.0.0
└── UNMET PEER DEPENDENCY @zowe/imperative@^4.0.0
```
The regex fails to match, and in this case returns null.


On Windows, the installOutput was:
```
+ @zowe/cics-for-zowe-cli@3.0.0
added 1 package from 1 contributor in 1.12s
```
And this regex matches successfully.

**Comment by tjohnsonBCM** [comment]
Discussion with @zFernand0 helped solve this issue, which was caused by having an old version of NPM installed that is not supported by Zowe CLI.

The following commands worked to upgrade NodeJS 8.x and NPM in Ubuntu 18.04:
```bash
sudo apt-get purge nodejs npm
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```
