### ISSUE TITLE
Add command to clear default profile

### ISSUE THREAD

**Issue by ghost** [zowe/imperative#305]
Currently there is no way to undo the action performed by the command `profiles set-default <profileName>`. To address this, @awharn suggested a command to clear the default profile.

There is already a `clearDefault` API function added in #304, this command could expose that function to the user.

If a user manually deletes a profile YAML file (not recommended but a plausible situation), it is possible for their default profile to become non-existent. The only way to fix this is to manually edit the `defaultProfile` setting in the meta YAML file for that profile's type. Adding this command would provide a better way to recover from such a situation.

**Comment by awharn** [comment]
This issue is requesting an enhancement to V1 profiles. V1 profiles are deprecated and no new enhancements are being accepted. Therefore, this issue is being closed.
