### ISSUE TITLE
help-web formatting problems with long, multiline descriptions

### ISSUE THREAD

**Issue by awharn** [zowe/imperative#319]
Multi-line descriptions of commands result in an additional command entry on the web help. It also creates a link to a page that does not exist, resulting in a file not found error.

![helpwebissue](https://user-images.githubusercontent.com/53578529/68488651-8b203780-0213-11ea-9720-37ce0139eaff.PNG)

**Comment by zFernand0** [comment]
Another instance where this might be occurring. Thanks @MikeBauerCA 
![image (1)](https://user-images.githubusercontent.com/37381190/69169392-47a4b380-0ac6-11ea-8949-8481cbed7ea0.png)
