### ISSUE TITLE
Plugin validation fails when using chained handlers

### ISSUE THREAD

**Issue by davcanalis** [zowe/imperative#320]
Plugin validation fails for command with chainedHandlers defined with message "CmdError: Command name = '***' has no 'handler' property", resulting in plugin commands not available.

**Comment by Joe-Winchester** [comment]
@MikeBauerCA - I got pinged by a customer last week asking about this issue saying that  

```
Plugin validation fails for command with chainedHandlers defined with message "CmdError: Command name = '***' has no 'handler' property", resulting in plugin commands not available.
```

Is this something you've come across before ?  I'm wondering if there is any more information needed to look into the issue more (it's not something I know enough about to be knowledgeable but I know it is blocking the customer moving forward with deploying their CLI extension).

**Comment by MikeBauerCA** [comment]
@Joe-Winchester do you have any more details on what the customer is doing? Are they building a new plug-in or installing an existing plug-in?

**Comment by davcanalis** [comment]
Hi guys,
I had a look at the issue yesterday. The problem is that developing a plugin with a command with chainedHandlers will result in a validation error, as reported in github issue. Inspecting the code, I suspect that the issue is in validatePluginCmdDefs method in this class:
imperative<https://github.com/zowe/imperative>/packages<https://github.com/zowe/imperative/tree/master/packages>/imperative<https://github.com/zowe/imperative/tree/master/packages/imperative>/src<https://github.com/zowe/imperative/tree/master/packages/imperative/src>/plugins<https://github.com/zowe/imperative/tree/master/packages/imperative/src/plugins>/PluginManagementFacility.ts
Requiring each command definition of “type”:”command” to have a “handler” property defined.
Hope this can help.

Thanks & Regards
Davide Canalis
Software Engineer
HCL Software Division <https://www.hcltech.com/software>

[cid:25ca4bd3-fa2e-4291-8d12-6182193472b0@apcprd04.prod.outlook.com]

**Comment by zFernand0** [comment]
for reference:
https://github.com/zowe/imperative/blob/master/packages/imperative/src/plugins/PluginManagementFacility.ts#L1120
