### ISSUE TITLE
Web-Help - Subgroups should display as another sub-heading

### ISSUE THREAD

**Issue by zFernand0** [zowe/imperative#323]
The subgroup seems to appear on the same.
```
#### Group
command | cmd - Run a command
list | ls - List objects. #### subGroup
```

**Comment by tjohnsonBCM** [comment]
@zFernand0 Is there a CLI plugin that has command subgroups so that I can test this?

**Comment by t1m0thyj** [comment]
Found one, if @broadcom/caview-for-zowe-cli is installed, the Groups header for "zowe caview list" isn't parsed correctly:
![image](https://user-images.githubusercontent.com/22344007/122596896-8e5ae680-d038-11eb-8a93-14935faccbf2.png)
