### ISSUE TITLE
allow values wrong matching

### ISSUE THREAD

**Issue by eberrio** [zowe/imperative#326]
Hi team, I have a list of allow values like " ERROR WAITING" that can be passed as an option of a command type array; when I pass a value like ERRORR or ERRORD it is considered as an allowed value but it does not match the specific value on the list.

thanks in advance for your assistance

**Comment by liuxh0** [comment]
Diving into the code, it says `values` in `allowableValues` are **regular expressions**.

https://github.com/zowe/imperative/blob/72d77a61cc5b9304373d21d60c232eb92f84910f/packages/cmd/src/doc/option/ICommandOptionAllowableValues.ts#L17-L25

As a result, `ERRORR` is a match of regex `/ERROR/`. So I don't think this is a bug.

You can use `^ERROR$` to only match `ERROR`.

**Comment by zFernand0** [comment]
Thanks @liuxh0 for fixing

**Comment by eberrio** [comment]
Hi thanks for the answer.

**Comment by zFernand0** [comment]
Fixed in Imperative 4.5.6 😄 
Will be included in Zowe CLI soon 😉
