### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by zFernand0** [zowe/imperative#327]
In order to take advantage of newer features and apply some patches, we need to:
- [x] Remove unused dependencies (see [comment](https://github.com/zowe/imperative/issues/327#issuecomment-560445833) below)
  Assigned: @awharn 
  Status: Complete ([imperative#334](https://github.com/zowe/imperative/pull/334), [zowe-cli#618](https://github.com/zowe/zowe-cli/pull/618), [perf-timing#19](https://github.com/zowe/perf-timing/pull/19))

- [x] `npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5`
  Assigned: @awharn 
  Status: Complete (#336)

- [x] Upgrade yargs from 8.0.2 to 15.0.2 (see #333 for details)
  Assigned: @tjohnsonBCM
  Status: Complete (#337)

- [x] Update Typescript to `3.7.x` since it contains a lot of "quality of life" enhancements as well as some patches. Go to the [Typescript 3.7 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) for more details
  Assigned: -
  Status: -

- [x] ~~Replace the soon-to-be-deprecated `tslint` with `eslint`. There are [resources](https://github.com/typescript-eslint/tslint-to-eslint-config) dedicated to help with this migration already.~~
  Assigned: -
  Status: On Hold (see #343 for details)

- [x] Ensure that all unit & integration tests pass on both Node 10 and 12 (there seem to be snapshot differences based on how JSON objects are printed)
  Assigned: @tjohnsonBCM 
  Status: PR Open (#345)

**Comment by tjohnsonBCM** [comment]
Another thing that would be good to do as part of this effort: We should look for and remove unused dependencies.

According to [depcheck](https://www.npmjs.com/package/depcheck) there are several, some of which are false positives but others appear to be valid. For example, there are `@types/X` packages present in the devDependencies that do not have a corresponding package `X` listed.
