### ISSUE TITLE
Update Imperative yargs dependency to fix security vulnerability

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/imperative#333]
We need to update the `yargs` dependency from 8.x to 15.x (see [the `yargs` changelog](https://github.com/yargs/yargs/blob/master/CHANGELOG.md) for list of breaking changes).

**Comment by YuanboXue-Amber** [comment]
Hi I'm from endevor. I want to publish a new version of our zowe plugin and keep getting my jenkins build failed because of this issue. 
Will this failed step stop me from publishing?

**Comment by zFernand0** [comment]
Hey @YuanboXue-Amber,
Please feel free to skip the auditing stage in your pipeline for now.
We should be releasing a new version of imperative within the next couple of days (hopefully)

**Comment by YuanboXue-Amber** [comment]
Thanks for the reponse :) We are going out with skipping the step

**Comment by tjohnsonBCM** [comment]
Some integration tests in Zowe CLI are breaking with the new yargs version, because of a breaking change made in 14.0 to "not allow additional positionals in strict mode".

**Comment by tjohnsonBCM** [comment]
We may want to downgrade the version of the `yargs` dependency used in Imperative from 15.x to 13.x. 13.x does not have the vulnerability found in 8.x, and also does not have the breaking change introduced in 14.x that seems difficult for us to handle.

**Comment by tjohnsonBCM** [comment]
Consulted with team and decided that this breaking change in command error output is acceptable. May want to investigate it further in the future, which can be tracked in #344.
