### ISSUE TITLE
Replace the soon-to-be-deprecated TSLint with ESLint

### ISSUE THREAD

**Issue by ghost** [zowe/imperative#343]
TSLint will stop receiving security fixes on December 1, 2020 ([roadmap](https://github.com/palantir/tslint/issues/4534#issue-413722441)).

There is a tool ([tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config)) dedicated to help with this migration already. It does not yet support all the TSLint rules used by Imperative (4 rules do not yet have ESLint equivalents), but is undergoing active development so may be more useful in a few months.

**Comment by t1m0thyj** [comment]
When we migrate to ESLint, we should consider enabling the `import/no-unresolved` rule with the caseSensitive flag enabled: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md#casesensitive

This would prevent some problems we've encountered before with imports that work on Windows, but fail on Linux where paths are case-sensitive.
