### ISSUE TITLE
Overall line coverage seems to be below 80%

### ISSUE THREAD

**Issue by zFernand0** [zowe/imperative#352]
```
-------------------------------------|----------|----------|----------|----------|

File                                 |  % Stmts | % Branch |  % Funcs |  % Lines |

-------------------------------------|----------|----------|----------|----------|

All files                            |    78.67 |    70.74 |    77.91 |     78.7 |

```

**Comment by t1m0thyj** [comment]
We're now barely above 80% in master branch:
![image](https://user-images.githubusercontent.com/22344007/108357808-f220f000-71bb-11eb-984a-e1feb671dcd6.png)

And even better in next branch:
![image](https://user-images.githubusercontent.com/22344007/108357875-0533c000-71bc-11eb-85c2-d3d04efe8b0f.png)

Can this issue be closed, or do we want to keep it open until we're comfortably above 80% in master branch?

**Comment by awharn** [comment]
I think we should keep it open for a bit longer. We've seen how the coverage changes a little bit in either direction every time we run tests (unless that was fixed), and 0.02% is barely scraping by. I'd also be more comfortable if statement and line coverage were above 80%, but that's just me, and probably outside the scope of this issue.

**Comment by zFernand0** [comment]
hey @awharn and @t1m0thyj, should this be closed now?
I bleieve we are above 82% currently 😋

**Comment by awharn** [comment]
I think we can close it. 😄

**Comment by zFernand0** [comment]
thank you!
