### ISSUE TITLE
Export IRestOptions type

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/imperative#356]
The type `IRestOptions` which was added in #348 should be exported, so that it can be imported by CLI plugins that use Imperative.

This should be a simple change, it only requires adding a line in `packages/rest/index.ts`.

**Comment by Alexandru-Dumitru** [comment]
Missed that detail. My bad ☹️

**Comment by apsychogirl** [comment]
Hi, Can I work on this issue?

**Comment by zFernand0** [comment]
Hey @apsychogirl, Feel free to assign yourself to the issue and open a PR once ready to contribute 😄
