### ISSUE TITLE
Optional secure profile fields fail to load

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/imperative#364]
ssh profiles in zowe CLI have an optional field keyPassphrase which is marked as secure: true. If the user does not enter keyPassphrase when creating a profile, the value in the profile for keyPassphrase is `null`, but the SCS plugin still attempts to load it from the vault.

Reproduction:
Create an ssh profile with the SCS plugin installed with no keyPassphrase, then attempt to use it on a zowe uss issue ssh "ls" command

**Comment by tjohnsonBCM** [comment]
This won't be fixed in the SCS plugin which was mentioned in the issue until https://github.com/zowe/zowe-cli-scs-plugin/pull/11 is merged.

**Comment by tjohnsonBCM** [comment]
Fixed in https://github.com/zowe/zowe-cli-scs-plugin/pull/11
