### ISSUE TITLE
Bearer token support

### ISSUE THREAD

**Issue by YuanboXue-Amber** [zowe/imperative#386]
Hello, this is Amber.

Is there any support in imperative for using **Bearer** token in **Authentication** header? I couldn't find any for now. 
If there isn't, it's not a problem. I would make my own header.

I saw Cookie header is used for token. Could you let me know what's the reason for it?

Thank you.

**Comment by dkelosky** [comment]
Hi Amber - Bearer support is not in imperative.  APIML supports Cookie or Bearer for it's JWT, and z/OSMF supports Cookie with LTPA2.

If you add in Bearer support, would you add it in imperative?  Our team might end up needing / adding it in within this PI.

**Comment by YuanboXue-Amber** [comment]
Cool. Thanks for the answer. I'd love to do it in imperative.

**Comment by YuanboXue-Amber** [comment]
Could you grant me write permission?

**Comment by dkelosky** [comment]
I don't think I can.  Would you mind forking and submitting the PR that way?

**Comment by YuanboXue-Amber** [comment]
Oh yeah sure didn't think of that

**Comment by YuanboXue-Amber** [comment]
pull request #387
