### ISSUE TITLE
During a test run, global node_modules get polluted

### ISSUE THREAD

**Issue by VitGottwald** [zowe/imperative#389]
While running `npm run test`, I listed my globally installed modules and I saw this

```sh
> npm -g ls --depth 0
/Users/vit/.fnm/node-versions/v12.16.1/installation/lib
├── cmd-sample-cli@0.0.0 -> /Users/vit/github/imperative/__tests__/__integration__/cmd
├── hello-world-cli@0.0.0 -> /Users/vit/github/imperative/__tests__/__integration__/hello_world
├── imperative-test-cli@0.0.0 -> /Users/vit/github/imperative/__tests__/__integration__/imperative
├── npm@6.13.4
└── prettier@2.0.2
```

That does not look right. The test is breaking out of the encapsulation of the package and polluting global scope. Before (and after the test suite completes) I only have 

```sh
> npm -g ls --depth 0
/Users/vit/.fnm/node-versions/v12.16.1/installation/lib
├── npm@6.13.4
└── prettier@2.0.2
```

**Comment by zFernand0** [comment]
Is it safe to assume that Imperative is cleaning up after itself?

I understand that the main issues is that imperative shouldn't be invasive. : )
Maybe we should think about using `npx` as a prefix and just install those CLIs on a temp folder?

**Comment by VitGottwald** [comment]
It _looks_ like it is cleaning after itself. But breaking encapsulation and mutating global scope is always a problem, even if it feels only temporary. Do we know all the ways the test suite can fail? Is the cleanup performed properly in all of them? What happens when I run the test suite twice on the same machine, say for different branches? ...
I do not know why this is happening, but it looks like invitation for trouble so I wanted to let you know about it.

**Comment by zFernand0** [comment]
Also, it's possible that the root of the project ends up with a test directory `somehome` containing the following files:
```
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   someHome/.imperative-test-cli/profiles/secured/secured_meta.yaml
        new file:   someHome/.imperative-test-cli/settings/imperative.json
        new file:   someHome/.myproduct/plugins/plugins.json
        new file:   someHome/.myproduct/settings/imperative.json
```

It may be related, and I know other may have more information on this.
@lauren-li, @dkelosky, @tjohnsonBCM, anything else you can think of?

**Comment by dkelosky** [comment]
yes

**Comment by lauren-li** [comment]
> Also, it's possible that the root of the project ends up with a test directory `somehome` containing the following files:
> 
> ```
> Changes to be committed:
>   (use "git reset HEAD <file>..." to unstage)
> 
>         new file:   someHome/.imperative-test-cli/profiles/secured/secured_meta.yaml
>         new file:   someHome/.imperative-test-cli/settings/imperative.json
>         new file:   someHome/.myproduct/plugins/plugins.json
>         new file:   someHome/.myproduct/settings/imperative.json
> ```

I got a fresh clone of the imperative repository yesterday, and running tests off of the master branch added these files into my project's root directory. Github showed them as changes, so I deleted these files and re-ran the tests. The files did not come back again after the second run of tests was done.

@zFernand0 was also able to recreate the issue using a fresh clone of the repository. (I.e. the files were added after the first run of tests, but not after he deleted them and ran the tests a second time.)
