### ISSUE TITLE
cli plugins install causes error

### ISSUE THREAD

**Issue by JTonda** [zowe/imperative#39]
_From @AHumanFromCA on July 2, 2018 15:26_

The command `cli plugins install` doesn't list help and instead throws an error.

The solution to this would be to have the plugin group follow the overall UX created for the other commands. So the install command would become something like:

```
cli plugins install plugin <plugin...>
```

_Copied from original issue: gizafoundation/imperative#121_

**Comment by gejohnston** [comment]
The "plugins install" no longer throws an error. It currently re-installs all previously installed plugins. There have been no consumer complaints about the current behavior.
