### ISSUE TITLE
Array values in profile are not provided to plugin, however option overrides are. (Zowe 1.5)

### ISSUE THREAD

**Issue by scifipony** [zowe/imperative#395]
I have a situation where I coded the option.  Note that it is an _array_.
```
     public static EJES_OPTION_NO_COLOR: ICommandOptionDefinition = {
        name: "no-color",
        aliases: ["nc"],
        description: "Accessibility option: Specify to prevent colorization of the CLI.  Same effect as defining NO_COLOR or FORCE_COLOR=0.",
        type: "array",
        group: EjesSession.EJES_CONNECTION_OPTION_GROUP
    };
```
As a connection option, it is in the profile.  So a I created a profile named zowezowe and made it the default profile.
```
-
  name:     zowezowe (default)
  contents:
    protocol:           https
    host:               sysplex.any
    port:               7554
    userid:             JoeUser
    password:           secret
    rejectUnauthorized: false
    basePath:           /api/v1/acme
    colorScheme:        mono
    nocolor:
      - on
    user:               JoeSuperUser
PS C:\Users\Robert\projects\eclipse\zowe>
```
All fine and good, so far.  The property ```nocolor``` is an array with the first element set to ```on```.  When I run the plugin, however, the plugin receives neither a ```nc``` nor a ```nocolor``` value array.  I get a value for all the other items—which are not arrays.  Here's a dump of the argument array:
```
{
  '$0': '..\\..\\..\\AppData\\Roaming\\npm\\node_modules\\@zowe\\cli\\lib\\main.js',
  'base-path': '/api/v1/acme',
  'color-scheme': 'mono',
  'reject-unauthorized': false,
  _: [
    'ejes',
    'e',
    'b',
    [length]: 3
  ],
  basePath: '/api/v1/acme',
  bp: '/api/v1/acme',
  colorScheme: 'mono',
  cs: 'mono',
  dbg: 1024,
  debug: 1024,
  host: 'sysplex.any',
  pass: 'secret',
  password: 'secret',
  port: 7554,
  prot: 'https',
  protocol: 'https',
  pw: 'secret',
  rejectUnauthorized: false,
  ru: false,
  scheme: 'mono',
  user: 'JoeSuperUser'
}
```
Here's the kicker.  If I run, specifying the overriding option ```--nc off```, I _do_ get the array with the value specified on the command line.  Here's the new dump.
```
{
  '$0': '..\\..\\..\\AppData\\Roaming\\npm\\node_modules\\@zowe\\cli\\lib\\main.js',
  'base-path': '/api/v1/acme',
  'color-scheme': 'mono',
  'no-color': [
    'off',
    [length]: 1
  ],
  'reject-unauthorized': false,
  _: [
    'ejes',
    'e',
    'b',
    [length]: 3
  ],
  basePath: '/api/v1/acme',
  bp: '/api/v1/acme',
  colorScheme: 'mono',
  cs: 'mono',
  dbg: 1024,
  debug: 1024,
  host: 'sysplex.any',
  nc: [
    'off',
    [length]: 1
  ],
  noColor: [
    'off',
    [length]: 1
  ],
  pass: 'secret',
  password: 'secret',
  port: 7554,
  prot: 'https',
  protocol: 'https',
  pw: 'secret',
  rejectUnauthorized: false,
  ru: false,
  scheme: 'mono',
  user: 'JoeSuperUser'
}
```
This looks like a bug.  Even if an array option is stored in the profile, it is never provided to the plugin.  As stated, I am still using 1.5, not the LTS, so this might have been fixed.

**Comment by scifipony** [comment]
When I change the definition to:
```
    public static EJES_OPTION_NO_COLOR: ICommandOptionDefinition = {
        name: "no-color",
        aliases: ["nc"],
        description: "Accessibility option: Specify to prevent colorization of the CLI.  Same effect as defining NO_COLOR or FORCE_COLOR=0.",
        type: "array",
        defaultValue: ["on"],
        group: EjesProfile.EJES_CONNECTION_OPTION_GROUP
    };
```
I added the ```default value``` property, the plugin receives the ```no-color```, ```noColor```, and ```nc``` arrays.  There is a discrepancy, here.  If there is a ```default value``` property, omitting the command line option provides an array with the default value.  Using the command line option without an argument, doesn't give you the default value as expected.  Instead you get an empty array.  This is okay, btw.   To make it even more interesting, if I store in the profile an empty array, the plugin receives an empty array.

There is a problem with _not_ specifying the ```default value``` property.

**Comment by gejohnston** [comment]
Since this was reported against a very old version of imperative, and we are unaware of such misbehavior with the array type of option in the current version, I am closing this issue.

If such behavior occurs in the current version, a new issue can be opened.
