### ISSUE TITLE
Enhancement: Login and logout commands for auth services

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/imperative#405]
As part of the effort to support MFA and SSO in Zowe CLI (https://github.com/zowe/zowe-cli/issues/718), enhance Imperative to support authentication services connected to profiles.

The following commands should automatically be generated for each authentication service:
* `zowe auth login <serviceName>`
* `zowe auth logout <serviceName>`

**Comment by tjohnsonBCM** [comment]
List of tests that must be added:
* [x] `CommandPreparer.prepare` / `CommandPreparer.appendAutoOptions` - Runs for every CLI command. Modified to add any option definitions from base profile that are missing in service profile (e.g., tokenType, tokenValue).
* [ ] `Imperative.addAutoGeneratedCommands` - Runs once for the root command definition. Modified to add "auth" command group if any profile types have an associated "authConfig" property.
* [ ] `CompleteAuthGroupBuilder` / `AuthCommandBuilder` / `AuthLoginCommandBuilder` / `BaseAuthHandler` - Added to automatically generate "auth login" commands.
* [ ] `AuthLogoutCommandBuilder` / `BaseAuthHandler` - Added to automatically generate "auth logout" commands.
* [x] `cmd-cli` - Integration tests for login
* [ ] `cmd-cli` - Integration tests for logout

**Comment by awharn** [comment]
Here is my understanding how login should work:

- Base profile exists
  - Login using existing profile and command line specified options
    - Prompt for missing host, port, user, password
  - Get the tokenType and tokenValue
  - Store tokenType and tokenValue in base profile
  - Do not delete username or password if stored in base profile

- Base profile does not exist, show token specified
  - Login using command line specified options
    - Prompt for missing host, port, user, password
  - Get the tokenType and tokenValue
  - Print to stdout
  - Do not store information in a base profile

- Base profile does not exist, show token not specified
  - Login using command line specified options
    - Prompt for missing host, port, user, password
  - Get the tokenType and tokenValue (to validate correctness of user info)
  - Prompt user: "The CLI requires that the host, port, and token must be stored on disk for use with future commands. Is this okay? [y/N]"
    - If user specifies yes: host, port, tokenType, tokenValue saved to profile named "default" and message is printed showing how to issue the profile update help command.
    - If user specifies anything else, nothing is stored to disk and login fails.

**Comment by tjohnsonBCM** [comment]
Resolved by #412
