### ISSUE TITLE
Plugin Management Facility should not imply multiple uninstall

### ISSUE THREAD

**Issue by JTonda** [zowe/imperative#41]
_From @zFernand0 on June 28, 2018 14:18_

Looking at the help of the uninstall command
```
USAGE         
-----      
 
  "test_cli\TestCLI.ts" plugins uninstall [plugin...] [options] 
```

It makes you think that you can uninstall multiple plugins with one single command like:
`$ ts-node "test_cli\TestCLI.ts"  plugins uninstall normal-plugin normal-plugin-2`

But instead it errors with:
```
Command Error:
Uninstall Failed
Error Details:
Plugin name ' normal-plugin,normal-plugin-2' is not installed.
```

- Solutions
  - Maybe we should NOT have the ellipsis (`...`) in the command definition
  imperative/packages/imperative/src/plugins/cmd/uninstall/uninstall.definition.ts

Line 45

 name: "plugin...", 
  - OR just support an array of strings and split by commas (`,`)

---
Full command and output
```
$ ts-node "test_cli\TestCLI.ts"  plugins uninstall normal-plugin normal-plugin-2
Command Error:
Uninstall Failed
Error Details:
Plugin name ' normal-plugin,normal-plugin-2' is not installed.
```

_Copied from original issue: gizafoundation/imperative#117_

**Comment by JTonda** [comment]
_From @AHumanFromCA on June 29, 2018 14:1_

That's odd, it used to work just as you expected it to work. Perhaps this is a bug that was introduced in all of our iterations of the facility itself?

**Comment by lyzla01** [comment]
I just looks at the current code,

currently the code in 
```
packages\imperative\src\plugins\cmd\uninstall\uninstall.handler.ts
```
does not parse input for multiple plugins.  we probably will have to add that if we want to support uninstall multiple plugins.

**Comment by gejohnston** [comment]
The 'plugins uninstall' currently successfully uninstalls multiple plugins if multiple plugin names are supplied on the command line.

```
zowe plugins uninstall @broadcom/endevor-for-zowe-cli @broadcom/jclcheck-for-zowe-cli
Removal of the npm package(s) was successful.
