### ISSUE TITLE
Allow plugins to designate secure fields to be censored in logs

### ISSUE THREAD

**Issue by ghost** [zowe/imperative#417]
Currently Imperative has a hardcoded list of CLI options which are masked in log output:
https://github.com/zowe/imperative/blob/168d945775b9c4a2e1988e194d2c25d1ab927a53/packages/logger/src/LoggerUtils.ts#L17-L18

CLI plugins may have additional options with secure values that they want to censor. Currently plugins are responsible to perform this additional censoring. There is potential for security enhancement if Imperative automatically masks these values:
* Perhaps plugins could add values to the CENSORED_OPTIONS definition
* Perhaps Imperative could detect CLI options associated with profile fields that have `secure: true` set, and censor values for these options

**Comment by zFernand0** [comment]
Hey @t1m0thyj,
Any thoughts?

**Comment by t1m0thyj** [comment]
> Perhaps Imperative could detect CLI options associated with profile fields that have secure: true set, and censor values for these options

This was implemented in https://github.com/zowe/imperative/pull/691.

> Perhaps plugins could add values to the CENSORED_OPTIONS definition

This is also possible now, since plugins can set values as secure in the team config file.
