### ISSUE TITLE
Profiles with optional secure fields cannot be deleted if options not set

### ISSUE THREAD

**Issue by JTonda** [zowe/imperative#42]
_From @AHumanFromCA on June 26, 2018 19:31_

## From the Endevor plugin folks

Also, another problem that they are having:

If I create a profile like:
endevor profiles create endevor system_12345 --host system -p 12345 --ow
type: endevor
name: system_12345
hostname: system
port: 12345
username: null
password: null
protocol: http
rejectUnauthorized: false

Then I try to delete it:
endevor profiles delete endevor system_12345
Command Error:
An error occurred attempting to load all profiles of every type. Load List:
Loading "system_12345" of type "endevor"
Error Details: "Unable to load the secure field "username" associated with the profile "system_12345" of type "endevor"."

This is not right.....

## My Take

Looks like we try to access the credentials on the system and that will fail if they were never set. So if we see a null stored in the profile, we should assume that no credentials exist on the system.

We need to be careful to ensure that credentials get deleted if a property goes from securly stored to null. So keep that in mind.

_Copied from original issue: gizafoundation/imperative#115_

**Comment by t1m0thyj** [comment]
This issue is related to zowe/zowe-cli#665 and should be fixed by #365 and zowe/zowe-cli-scs-plugin#7
