### ISSUE TITLE
Random codecov diffs

### ISSUE THREAD

**Issue by mheuzey** [zowe/imperative#461]
When opening #458, I noticed that the codecov report initially showed some lines losing coverage in a file that I had not touched (CommandResponse.ts). The diff disappeared and reappeared as I made minor adjustments to the PR (no code changes). Looking into this topic of random codecov diffs, I found a thread which suggested that the tests might be non-deterministic. So I ran the unit test for that file on my local machine a few times, and it does look like the coverage changes between runs.

![image](https://user-images.githubusercontent.com/32349430/98859690-8b5ba000-2430-11eb-85a3-6a6858bbab90.png)

I'm not an expert on tests, but I figured I would bring this up so someone with more knowledge could verify whether something in the test suite could be causing random coverage changes. I don't know how widespread this problem is, but looking over the last few PRs, I see that #456 and #435 both have the same coverage diff as mine, and both PRs made small changes that shouldn't have affected coverage.

**Comment by JTonda** [comment]
We believe that updates to the codecov tools have eliminated this problem therefore we are closing this issue.
