### ISSUE TITLE
Plugin Validation Failure returns 0

### ISSUE THREAD

**Issue by awharn** [zowe/imperative#463]
Plugin validation returns 0 regardless of whether or not validation succeeded. This is a problem for scripts, as they cannot check whether or not an installation of a plugin succeeded. This also may mask a problem if a user is attempting to install plugins in bulk, causing the error message to be buried and making it more difficult for a user to identify that a plugin is missing.

```
_____ Validation results for plugin '********' _____

*** CmdError: The handler for command = 'command1 (at depth = 2)' does not exist: /root/.zowe/plugins/installed/lib/node_modules/***********

*** CmdError: The handler for command = 'command2 (at depth = 2)' does not exist: /root/.zowe/plugins/installed/lib/node_modules/***********

This plugin has command errors. No plugin commands will be available.


root@test-vm:~# echo $?
0
```

**Comment by liuxh0** [comment]
I found out that calling `params.response.console.error()` does not result in an exit code greater than zero. Here are some ideas:

- The easiest way I can think of is to throw a string in the `ValidateHandler`'s `process()` function to trigger a "Command Error". 
https://github.com/zowe/imperative/blob/a6dbcc5a7b997f1eb9ee4d474e18f965531db665/packages/imperative/src/plugins/cmd/validate/validate.handler.ts#L47

- An alternative is to call `CommandResponse`'s `failed()` function whenever `params.response.console.error()` is called.
https://github.com/zowe/imperative/blob/a6dbcc5a7b997f1eb9ee4d474e18f965531db665/packages/cmd/src/response/CommandResponse.ts#L556
