### ISSUE TITLE
Single Profile - CLI Initialization Failure

### ISSUE THREAD

**Issue by awharn** [zowe/imperative#465]
On a Linux system without a desktop environment (i.e. Jenkins, Linux Servers / VMs, Docker), keytar is installed successfully but fails to initialize.

The current implementation of the `DefaultCredentialManager` (specifically `loadCredentials`, `saveCredentials`, and `deleteCredentials`) do not handle this issue, and this in turn prevents the CLI from running any commands when any credential is stored as secure on the user configuration. `checkForKeytar` also doesn't handle this, as it only checks for the existence of keytar, and never attempts to use it.

Imperative error handling makes this difficult to trace, as it seems to throw a new error, destroying any traceback, but the following is the message received:

```
[2020/11/19 20:11:17] [FATAL] [main.js:48] Error initializing Zowe CLI:
 ImperativeError: UNEXPECTED ERROR ENCOUNTERED
    at Function.<anonymous> (/home/jenkins/imperative/lib/imperative/src/Imperative.js:271:21)
    at Generator.throw (<anonymous>)
    at rejected (/home/jenkins/imperative/lib/imperative/src/Imperative.js:16:65) {
  mDetails: {
    msg: 'UNEXPECTED ERROR ENCOUNTERED',
    causeErrors: [Error: Error calling StartServiceByName for org.freedesktop.secrets: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.freedesktop.secrets: Operation not permitted]
  },
  mMessage: 'UNEXPECTED ERROR ENCOUNTERED'
```

**Comment by awharn** [comment]
This seems to be caused by `this._vault.load(Config.SECURE_ACCT)` in Config.ts. Once this line is wrapped in a try-catch block, the CLI will initialize.

**Comment by t1m0thyj** [comment]
Fixed in https://github.com/zowe/imperative/pull/480:
> Don't throw error in Config.load when secure vault fails to initialize. We can prompt for values instead.
