### ISSUE TITLE
[single-profile] Expose the `secure` property in zowe config set-secure

### ISSUE THREAD

**Issue by zFernand0** [zowe/imperative#474]
This should allow users to retrieve values out of their vault and place them back in the corresponding config file.

Ideas:
`zowe config set-secure profiles.lpar1.properties.my_service.user --no-secure`
`zowe config set-secure profiles.lpar1.properties.my_service.user --secure false`
`zowe config set-unsecure profiles.lpar1.properties.my_service.user`

Location in code:
https://github.com/zowe/imperative/blob/5bb73720d066d5ab58f6be59c4a57d7975d89709/packages/imperative/src/config/cmd/set-secure/set-secure.handler.ts#L63

**Comment by t1m0thyj** [comment]
Added in https://github.com/zowe/imperative/pull/484

`set-secure` has been renamed to `set` and we now support `zowe config set profiles.lpar1.properties.my_service.user --secure false`
