### ISSUE TITLE
zowe config init does zowe always store new password

### ISSUE THREAD

**Issue by dkelosky** [zowe/imperative#513]
1. `zowe config init` and answer prompts
2. `zowe config list` (as of now) to see current passwords:
```
  my_base:
    type:       base
    properties:
      rejectUnauthorized: true
      user:               fakeuser
      password:           fakepass
```
3. `zowe config init` again and answer prompts with new values
4. `user` and `password` are the values from step 1

**Comment by zFernand0** [comment]
@t1m0thyj Should this be closed?

**Comment by t1m0thyj** [comment]
@zFernand0 Yes, I suggest we close it since neither of us can reproduce the issue anymore 🙂
