### ISSUE TITLE
zowe config secure within home directory doesn't save global credentials

### ISSUE THREAD

**Issue by dkelosky** [zowe/imperative#527]
1. clear credential manager values for zowe
2. `zowe config init --global --no-prompt`
3. cd to ~/<home>/.zowe
4. `zowe config secure` and respond to prompts
5. add valid host / port
6. try a zowe command, e.g. `zowe jobs list jobs` and see a prompt for `user`

As a work around, if I add `--global` to `zowe config secure` I no longer get prompted.  However, this seems like inconsistent behavior in that I cannot run `secure` on a config in my current working directory.

**Comment by t1m0thyj** [comment]
@dkelosky This works for me now, good to close?

**Comment by dkelosky** [comment]
thanks
