### ISSUE TITLE
Paths in secure properties object should be case insensitive

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/imperative#546]
...at least on Windows.

Zowe CLI stores properties under a path with upper case drive letter like "C:\dev".

VS Code APIs provide paths with lower case drive letter like "c:\dev".

**Comment by t1m0thyj** [comment]
This could be fixed with the [true-case-path](https://www.npmjs.com/package/true-case-path) package.

Perhaps it makes sense to delay fixing this issue until we've decided how to address zowe/zowe-cli#950, in case we decide to abandon the current method of associating secure properties with file paths.

**Comment by t1m0thyj** [comment]
Maybe this isn't really an issue with our config API, and it's just an oddity of VS Code's APIs?

Here's an example of a VS Code extension published by Microsoft which has to fix drive casing on Windows:
https://github.com/microsoft/vscode-go/blob/9ee1f173b05bb74ee64e4906f832603cd7380687/src/util.ts#L841-L854

**Comment by MikeBauerCA** [comment]
@t1m0thyj do you think we still need to consider using this true-case-path package?

**Comment by t1m0thyj** [comment]
I'm good to close this, we recommended that VS Code extensions use the `true-case-path` package in [our Medium blog about ProfileInfo](https://medium.com/zowe/an-api-to-simplify-retrieval-of-zowe-profile-information-a1293656de21). It seems more like a VS Code issue/oddity that the paths have non-standard casing, rather than a bug in our API.
