### ISSUE TITLE
Move to ESLint

### ISSUE THREAD

**Issue by mheuzey** [zowe/imperative#578]
TSLint has been [deprecated ](https://github.com/palantir/tslint/issues/4534) in favor of ESLint. TSLint rules should be converted to ESLint rules.

- https://github.com/typescript-eslint/tslint-to-eslint-config
- https://github.com/typescript-eslint/typescript-eslint
- https://github.com/typescript-eslint/tslint-to-eslint-config/blob/main/docs/FAQs.md

**Comment by t1m0thyj** [comment]
Related to https://github.com/zowe/imperative/issues/343

**Comment by mheuzey** [comment]
You're right, that's the same issue. It's odd, I searched for both ESLint and TSLint, and that issue doesn't show up in the search results.
