### ISSUE TITLE
Labels in help text for options are not aligned

### ISSUE THREAD

**Issue by JTonda** [zowe/imperative#58]
_From @dogboydog on April 16, 2018 17:18_

Labels such as `(string)` in the help text are not aligned with each other 

![labels](https://user-images.githubusercontent.com/9920963/38824855-9c24a802-4178-11e8-883b-b8e6ec488e42.png)

_Copied from original issue: gizafoundation/imperative#42_

**Comment by gejohnston** [comment]
Such labels are correctly aligned in the current product.
