### ISSUE TITLE
Validate Checksum for public scripts (if possible)

### ISSUE THREAD

**Issue by zFernand0** [zowe/imperative#601]
To prevent for possible security breaches in the future, we could verify that the script is coming from a legit source before running it.

Information on how to validate a public script:
https://docs.codecov.io/docs/about-the-codecov-bash-uploader#validating-the-bash-script

Same could apply to other scripts if/when Zowe implements other tooling, for example:
https://github.com/blackducksoftware/synopsys-detect#build

**Comment by t1m0thyj** [comment]
If we update the version of "codecov/codecov-action" used in our GitHub workflow to 1.4.0 or newer, then the Bash script will be validated: https://github.com/codecov/codecov-action/releases/tag/v1.4.0

**Comment by t1m0thyj** [comment]
Codecov is also introducing a new uploader written in Node.js that should have better security, and has provided instructions for how to use and integrity check it: https://about.codecov.io/blog/introducing-codecovs-new-uploader/

Thanks to @awharn for the link 🙂

**Comment by t1m0thyj** [comment]
Our workflows are now using the new Codecov uploader `codecov/codecov-action@v3`.
