### ISSUE TITLE
ImperativeExpect Cannot Override All Error Messages

### ISSUE THREAD

**Issue by JTonda** [zowe/imperative#61]
_From @dkelosky on March 30, 2018 15:46_

One example is here: ImperativeExpect.ts.  Line 255

_Copied from original issue: gizafoundation/imperative#18_

**Comment by zFernand0** [comment]
hey @dkelosky, 
Is this still an issue?

**Comment by dkelosky** [comment]
i dont even know what this means anymore 😄
