### ISSUE TITLE
CommandPreparer, help-examples description typo

### ISSUE THREAD

**Issue by sosadchuk** [zowe/imperative#612]
Hello, this is a really small one.

https://github.com/zowe/imperative/blob/83511b7d04ab203cfee5d60db3958b954a8cade8/packages/cmd/src/CommandPreparer.ts#L440
->
<pre><code>in <b>a the</b> group</code></pre>

**Comment by namanpatel1112** [comment]
Created PR: https://github.com/zowe/imperative/pull/617

**Comment by namanpatel1112** [comment]
PR merged! I'll close the issue now.
