### ISSUE TITLE
"npm run test" completes with exit code 0 even if tests fail

### ISSUE THREAD

**Issue by JTonda** [zowe/imperative#62]
_From @dogboydog on March 21, 2018 16:22_

I think the gulp code needs to be adjusted to check for errors running the tests and reflect that in the exit code for the command and maybe a final message in the text output

**Comment by JTonda** [comment]
_From @AHumanFromCA on March 29, 2018 13:35_

Just an FYI, I have the pipeline constructed to not expect an error code from the test commands.

The commands now generate a junit report that the Jenkins machine can inspect and report on. If there is any failing test in that batch, the steps will successfully complete but the build will be marked as UNSTABLE (Yellow in blueocean)

If these tasks start throwing non-zero exit codes, then the pipeline will need to be adjusted so that the current behavior is not changed.

**Comment by gejohnston** [comment]
The pipelines have been re-written in GitHub Actions. A failing test correctly fails the pipeline.
