### ISSUE TITLE
IntelliSense not working in latest team profile schema

### ISSUE THREAD

**Issue by mheuzey** [zowe/imperative#624]
The IntelliSense doesn't seem to be working anymore with the latest version of team profiles schema. It appears to be related to the `dependentSchemas` field. 

![image](https://user-images.githubusercontent.com/32349430/123468349-a219c600-d5bf-11eb-9ede-778cc9139396.png)
If that field is removed, IntelliSense seems to work again.

![image](https://user-images.githubusercontent.com/32349430/123468453-c8d7fc80-d5bf-11eb-95f8-6353753a31e2.png)

**Comment by t1m0thyj** [comment]
When we update the schema to fix this, we may also want to update the `$schema` URL to use the 2020-12 schema, which makes the VS Code warning about using a draft schema disappear. Thanks to @mheuzey for pointing this out 🙂

**Comment by zFernand0** [comment]
This issue should be addressed in the latest version

**Comment by zFernand0** [comment]
Fixed in `@zowe/imperative@5.0.0-next.202107092101`
CLI update coming up😋
