### ISSUE TITLE
Single character options accessed w/ single dash (correct) but rendered in help w/ double-dash (incorrect)

### ISSUE THREAD

**Issue by robertblum-psi** [zowe/imperative#638]
In most command line interfaces, single character options use a single dash.  In Zowe, this seems to be true only when the single character option is defined as an alias.  

Nevertheless, single character options defined using the _name_ property _are_ accessible with a single dash option on the command line _but_ are rendered in the text and web help with double-dashes.  That they can be accessed with a single dash is only true by a quirk of Zowe's programming.  For an arbitrary sample option _c_, Zowe sends an argument array with a "c" property to provide the value to the program regardless of whether the user coded -c or --c on the command line.   In any case, Zowe does not flag it as an error.

For example, in an options array on a ICommandDefinition I have:
``
                { name: "c", group: QUERY_OPTIONS,
                        type: "string", description: "A list of comma separated, case-insensitive names of columns to include in...
``
Help renders this:

        --c  (string)
             A list of comma separated, case-insensitive names of columns to include in...

As pointed out above, Zowe doesn't break, but my Zowe program passes the _command line_ not its internal array to consumer modules.  Perhaps just as bad, _the help generated by Zowe is is flat out wrong_ as far as the user is concerned.  This application simulates an interface and uses options that reflect one character options in that interface.   The **-c** option is the **c** parameter.  I can't change that. 

I think assuming double dash for a single character option name is a design oversight.   I don't think it was intentional to assume all options will always have two dashes and that only an single character alias can have one dash.  That's...  I'm not sure what that is.   I don't know if this becomes a breaking change, or not.  If it is considered such, I'd vote for a NameIsSingleDash property being added.   Otherwise, see my first line above.

PS C:\Users\Robert> zowe -V
6.32.0

**Comment by t1m0thyj** [comment]
This has been fixed in Imperative and should make it into the next Zowe CLI update (likely 6.38.0).
