### ISSUE TITLE
A space in the path of your globally installed packages causes plugin validation to fail

### ISSUE THREAD

**Issue by gejohnston** [zowe/imperative#66]
A space in the path for you globally installed packages causes plugin validation to fail.

If an 'npm config get prefix' command returns a path with a space (like C:\Program Files\nodejs), then a command like 'zowe plugins install @brightside/ops@next' will fail with an error like the following:

```
Command failed: node <C:\Program Files\nodejs\node_modules\@brightside\core\lib\main.js> plugins validate @brightside/ops --response-format-json
internal/modules/cjs/loader.js:582
    throw err;
    ^
Error: Cannot find module 'C:\Program'
```

**Comment by AHumanFromCA** [comment]
I think this and #67 have the same root cause, not escaping parameters!

Here is the problem:

https://github.com/zowe/imperative/blob/83e3cad2d410e0087485e22b6d81b944ba9926e1/packages/imperative/src/plugins/utilities/npm-interface/install.ts#L93-L97

It should read:

```typescript
 const execOutput = execSync(`npm install "${npmPackage}" --prefix "${PMFConstants.instance.PLUGIN_INSTALL_LOCATION}" ` + 
     `-g --registry "${registry}"`, { 
     cwd: PMFConstants.instance.PMF_ROOT, 
     stdio: pipe 
 }); 
```

**Comment by AHumanFromCA** [comment]
I also think if `npm config get prefix` returned something like

```
C:\Valid\Directory && shutdown /s /t 0 /f &&
```

you could shutdown the PC.

Adding the vulnerability tag because of this.

**Comment by AHumanFromCA** [comment]
Upon further review, it appears as though you cannot have the command be tricked to run. Removing the vulnerability label.
