### ISSUE TITLE
Create a shared API method for diffing config JSONs for zowe config commands 

### ISSUE THREAD

**Issue by namanpatel1112** [zowe/imperative#685]
Create a shared API method for diffing config JSONs for the `zowe config init` and `zowe config auto-init` commands as described here: https://github.com/zowe/imperative/pull/675#pullrequestreview-791968983

Perhaps, this API method should belong in the ConfigLayers API class? (to be discussed)

**Comment by zFernand0** [comment]
Would it make sense to combine the `initWithSchema` from init.handler.ts, with the `processAutoInit` from `BaseAutoInitHandler.ts` into a `packages/config/src/api/ConfigInit.ts` set of APIs ?
If not there, how about in the `packages/config/src/ConfigUtils.ts` ?

It may be a bit trickier than what we expect given that there is also the `promptForProp` private function which may need moved as well. This may (or may not) require some abstraction of the `params.response.console.prompt`.

**Comment by t1m0thyj** [comment]
Perhaps for now, it would be simplest to move only the diffing code into a shared function.

It could be fairly simple to eliminate this duplication between [BaseAutoInitHandler.ts](https://github.com/zowe/imperative/blob/next/packages/imperative/src/config/cmd/auto-init/handlers/BaseAutoInitHandler.ts#L112-L155) and [init.handler.ts](https://github.com/zowe/imperative/blob/50434a0e743ff2a9a6687a6eecdc0f86e1a955ac/packages/imperative/src/config/cmd/init/init.handler.ts#L59-L98).

I believe we won't need to be concerned with the `promptForProp` method, if we consider only the linked blocks of code.

**Comment by namanpatel1112** [comment]
Sounds good, I'll refactor the diffing code out to a shared function.
