### ISSUE TITLE
Escape ANSI escape codes in help generator

### ISSUE THREAD

**Issue by sosadchuk** [zowe/imperative#704]
Hi,

We are using ANSI escape codes to highlight some description sections to keep the style consistent. For example - `Default value: error.log` provided as a part of description to have the same gray coloring as if we used the `defaultValue` property in option definition.

In web help, those codes are not stripped and look bad.

Attaching images with code definitions, terminal output and web help output.

Definitions:
<img src="https://user-images.githubusercontent.com/45584158/145832221-5e4b0f83-5b6e-4eea-ba3a-1a3bf91f46f1.png" width="90%" height="90%">

Terminal output:
<img src="https://user-images.githubusercontent.com/45584158/145832256-00da01dc-59ec-48eb-a7b1-2e0e14a5df98.png" width="45%" height="45%">

Web help output:
<img src="https://user-images.githubusercontent.com/45584158/145832300-b8290bad-0c44-4e48-a307-3f285cba86f8.png" width="55%" height="55%">

**Comment by t1m0thyj** [comment]
> For example - `Default value: error.log` provided as a part of description to have the same gray coloring as if we used the `defaultValue` property in option definition.

I think our recommendation here would be to use the `defaultValue` property rather than hardcoding ASCII escape codes to imitate it. Then the default value will be automatically handled by Imperative and displayed correctly in both terminal help and web help. Could you provide more details why using the `defaultValue` property is undesirable for your use case?

**Comment by sosadchuk** [comment]
> > For example - `Default value: error.log` provided as a part of description to have the same gray coloring as if we used the `defaultValue` property in option definition.
> 
> I think our recommendation here would be to use the `defaultValue` property rather than hardcoding ASCII escape codes to imitate it. Then the default value will be automatically handled by Imperative and displayed correctly in both terminal help and web help. Could you provide more details why using the `defaultValue` property is undesirable for your use case?

Hi, sorry for the delay with an answer. We have some output file parameters for commands and overwriting logic around them. For example the `error-file` mentioned above.

If the parameter value specified explicitly and the output file already exists -> we wil overwrite it.

But if the value is not provided, the default value of `error.log` will be assigned. Then if the file already exists, we will throw an error requesting to specify another filename / remove existing file / or specify `--error-file` value explicitly to overwrite existing file.

We do also have a profile option for overwriting without prompt, but that's not the case here :)

The thing is - we want users to be on a safe side and decide what to do with existing output files by themselves. If we specify a default value in a definitions file - we will be unable to differentiate whether the value was provided by the framework (default) or by a user when getting IHandlerParameters.arguments.

**Comment by sosadchuk** [comment]
I guess it would be great to have a replacement in `WebHelpGenerator.genCommandHelpPage()` using the https://github.com/chalk/strip-ansi or pattern from https://www.npmjs.com/package/ansi-regex

**Comment by sosadchuk** [comment]
Let me prepare a PR..
