### ISSUE TITLE
Documentation contains wrong samples

### ISSUE THREAD

**Issue by zszabo14** [zowe/imperative#728]
Hi

I've just seen the documentation was updated. I found that the samples are wrong for some commands, like 

https://docs.zowe.org/stable/web_help/index.html?p=zowe_zos-files_copy_data-set

the sample commands referring to rse-api-for-zowe-cli.

`zowe  **rse-api-for-zowe-cli** copy data-set "USER.FROM.SET" "USER.TO.SET"`

**Comment by MikeBauerCA** [comment]
Thanks, just to follow-up on the second request @zszabo14 - we do not currently intend to split the commands by organization. However, if you are only interested in a specific area, you could try to leverage the search bar in the upper left under `Tree View` or `Flat View` to limit results. If I may ask, why would you like to see commands split into sections based on which organization owns the plug-in? This information is also available on our [conformance site](https://www.openmainframeproject.org/projects/zowe/conformance).

**Comment by JamesBauman** [comment]
To complete issue #728.
