### ISSUE TITLE
[next] ProfileInfo API not returning an osLoc

### ISSUE THREAD

**Issue by zFernand0** [zowe/imperative#771]
When calling `ProfileInfo.getAllProfiles()`, the profiles in the global layer didn't have an osLoc specified, which prevented some Applications to be able to load all default profiles on load (e.g. Zowe Explorer)

Source code:
https://github.com/zowe/imperative/blob/e804c8bdd85f7704fcc0001548dc007bc7695b9e/packages/config/src/ProfileInfo.ts#L1190-L1191

By removing `this.mLoadedConfig.mActive.global === layer.global` from the condition, it allows the `findTeamOsLocation` to return all `osLoc`s where the given profile is found.

This may have unintended consequences to application developers since it may cause the application to load all default profiles it can find (including default ones in the global layer)

---

**API Call:**
Before
![image](https://user-images.githubusercontent.com/37381190/161603519-e5790159-549e-44e9-b5ce-1d5530040519.png)

After
![image](https://user-images.githubusercontent.com/37381190/161603360-56038434-b5a8-4483-a8d7-08c32c5f19b6.png)

**Zowe Explorer Implementation:**
Before
![image](https://user-images.githubusercontent.com/37381190/161602801-f39959c6-699a-4f00-9718-d24b80785a51.png)

After
![image](https://user-images.githubusercontent.com/37381190/161603092-92bf38be-a7ca-4fc5-bc46-9449a210a840.png)

**Comment by davidkjackson54** [comment]
This is a problem. 
Although I do not explicitly use osLoc within my own code, my code  fails when attempting to perform:
`mergedArgs: profInfo.mergeArgsForProfile(element, { getSecureVals: true }),`    
where element is an entry returned from profInfo.getAllProfiles("zmf")
