### ISSUE TITLE
Miscellaneous logging changes

### ISSUE THREAD

**Issue by PeteSwauger** [zowe/imperative#81]
Add command entered in readable format (similar to as shown entered on command line).

Fix message where string substitutions aren't done. "no unknown positionals. Length of positional arguments was: %s. Contents of _ were %s, Expected "_" to have length of %s"

Remove line 'this.log.trace(`Arguments supplied for... ' - redundant and output confusing

**Comment by gejohnston** [comment]
Cannot reproduce this behavior in the current product. Updates to the modules appear to have resolved this behavior.
