### ISSUE TITLE
`config init` discards values that it prompts for

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/imperative#821]
**Steps**
* Run `zowe config init --no-prompt` so that `profiles.base.properties.host` is an empty string
* Run `zowe config init` and enter a value for host when prompted

**Actual Behavior**
The `host` property in zowe.config.json is still an empty string

**Expected Behavior**
The `host` property in zowe.config.json is the value I entered when prompted

**Comment by zFernand0** [comment]
I like this template, maybe we can add `npm version` or `zowe --version`  (#84) 😋
