### ISSUE TITLE
Export the IAuthHandlerApi type from imperative package

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/imperative#839]
https://github.com/zowe/imperative/blob/master/packages/imperative/src/auth/doc/IAuthHandlerApi.ts

**Comment by aadityasinha-dotcom** [comment]
Hi @t1m0thyj can I worn on this issue?

**Comment by zFernand0** [comment]
There is a similar issue that might be good to work on at the same time as this one 
- https://github.com/zowe/imperative/issues/840 

😋
