### ISSUE TITLE
Create and document an issue template for the imperative repo

### ISSUE THREAD

**Issue by tucker01** [zowe/imperative#84]
We should create an issue template for the imperative repo. All issues should follow a consistent (and ideally parse-able) format.

**Comment by AHumanFromCA** [comment]
I agree with this so much that I gave it every reaction I could!

**Comment by gejohnston** [comment]
A template was created for the Zowe CLI repo because it was felt that consumers were more likely to open issues against that repo than the Imperative repo. A template for Imperative will be valuable, but is considered a lower priority.
