### ISSUE TITLE
requirePluginModuleCallback should always return an object

### ISSUE THREAD

**Issue by zFernand0** [zowe/imperative#85]
This function should always be returning an object (instead of a string) if we decided to just record the issue.
https://github.com/zowe/imperative/blob/09afc7e9275ecd0fffec889b7f3b5cfb5887bbd1/packages/imperative/src/plugins/PluginManagementFacility.ts#L359-L371

As a result of this, the ConfigurationLoader silently fails without any indication as to what happened.
https://github.com/zowe/imperative/blob/09afc7e9275ecd0fffec889b7f3b5cfb5887bbd1/packages/imperative/src/ConfigurationLoader.ts#L56-L71

In line 58, callerFileRequirer will return the string `"{}"`, and because of that it fails to assign `config.name = packageJson.name`

Why did we decided to catch the error from `requirePluginModileCallback` in the first place?

This issue was found thanks to @JamesBauman :smile:

**Comment by zFernand0** [comment]
Also, the `requirePluginModuleCallback` should be typed to return an object :smile:

**Comment by gejohnston** [comment]
The quotes have been removed from the statement 'return "{}";' in the requirePluginModuleCallback function. So, it currently always returns an object.
