### ISSUE TITLE
Disclaimer text contains "CA Technologies"

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/imperative#86]
When installing a plugin through any Imperative based CLI, you will see this text before the install starts:

```
Imperative CLI Framework plug-ins can gain control of your CLI application
legitimately during the execution of every command. Install 3rd party plug-ins
at your own risk. CA Technologies makes no warranties regarding the use of
3rd party plug-ins.
```

I don't believe that CA Technologies should be mentioned in this statement as the code is owned by the OMP community.

@MarkAckert could you check with the ZLC to see what this should be changed to?

**Comment by MarkAckert** [comment]
@jmertic John, any comments on the right language to use for a warning like this?

I think we could either make the warning generic (cut the last sentence out), or replace the entity reference to "Zowe Organization"/"Zowe Project"/OMP instead of "CA Technologies".

**Comment by jmertic** [comment]
Sorry for the delays here.

Since the codebase is under the EPLv2, many of the same assertions made with that statement are already part of the the EPLv2. It might be best to consult CA legal to understand what you are looking to address with that statement that the EPLv2 doesn't. Happy to have LF legal engage to discuss.

**Comment by AHumanFromCA** [comment]
I think the big thing that we want to keep here is the fact that a user is installing a 3rd party plugin and we make no warranties that the thing we are installing is safe and will work. I think we've determined that it isn't CA Technologies that should be specified but something referring to the Zowe Organization.

**Comment by jmertic** [comment]
Completely understand. Let's get a conversation on this topic between LF
and CA legal to determine the best solution.
<https://calendly.com/jmertic>

**Comment by zFernand0** [comment]
@MikeBauerCA, should this issue be closed?
