### ISSUE TITLE
Fix rendering objects in default profile values (both web-help & terminal based help)

### ISSUE THREAD

**Issue by sosadchuk** [zowe/imperative#870]
Hello,

We have one of our profile properties defined as follows:
```
  public static DBMDB2_CONNECTION_OPTION_ENVIRONMENT_LIST: ICommandOptionDefinition = {
    name: "environment-list",
    aliases: ["el"],
    description: `...`,
    defaultValue: {
      ssid1: "env1@host1:port1",
      ssid2: "env2@host2:port2"
    },
    type: "string",
    required: false,
    group: dbmDb2CommandOptionDefinitions.DBMDB2_CONNECTION_OPTION_GROUP
  };
```

For both V1 profiles and team configuration, the value is saved without any issues, but in the web-help and terminal we see:

![image](https://user-images.githubusercontent.com/45584158/185399906-98313894-faa5-44b3-ae49-a0b5021049ef.png)

![image](https://user-images.githubusercontent.com/45584158/185399995-ae2fe129-297e-498d-83c1-c6f463f31d88.png)

I assume we are supposed to provide a string value here, but that's the problem with defaults - while we can use a custom create/update handler for V1 profiles, we don't have a mechanism to convert string values (as we expect them to be provided) for team configuration.

The same limitation forces users to use `--json` flag while updating such fields in team configuration. But that's another story I guess, would be nice to see the string representation of the object at least.

Thanks,
Sergei.

**Comment by t1m0thyj** [comment]
In the example option definition that you provided, the `defaultValue` and `type` don't match. I would expect the definition to be one of the following:
```
    defaultValue: {
      ssid1: "env1@host1:port1",
      ssid2: "env2@host2:port2"
    },
    type: "json",
```
```
    defaultValue: `{\n  ssid1: "env1@host1:port1",\n  ssid2: "env2@host2:port2"\n}`,
    type: "string",
```
Could you please clarify which is the intended behavior for this option?

**Comment by zFernand0** [comment]
If the option type is a string and the default value is not a string, we could  `JSON.stringify` the default value.

**Comment by gejohnston** [comment]
The user $HOME directory plays no special role in the configuration overrides. The --global-config flag places the config file in the $ZOWE_CLI_HOME directory.

We feel that this use just a mistake in usage. We are closing this issues as working as designed.

**Comment by gejohnston** [comment]
Accidentally closed this issue. Reopening this issue.
