### ISSUE TITLE
read dependency is 7 years old

### ISSUE THREAD

**Issue by uzuko001** [zowe/imperative#886]
The `read` package's latest release - 1.0.7 was 7 years ago and it violates some policies for our projects which use zowe/imperative as a direct dependency. Would it be possible to update it with something more up to date?

**Comment by zFernand0** [comment]
Hey @sosadchuk,
This issue was opened due to a Broadcom _Above & Beyond_ Operational Policy.
We are happy to continue discussions offline.
Locking this thread for now.
