### ISSUE TITLE
ProfileInfo: Add support for any properties specified in `zowe.config.json`

### ISSUE THREAD

**Issue by zFernand0** [zowe/imperative#899]
We will want to make available all properties contained in a `zowe.config.json` file regardless of whether they are defined in the `zowe.schema.json` file.

_Originally posted by @zFernand0 in https://github.com/zowe/vscode-extension-for-zowe/issues/1667#issuecomment-1307525441_

**Comment by adam-wolfe** [comment]
*Adding the `keep` label because this is a prerequisite of https://github.com/zowe/vscode-extension-for-zowe/issues/1667
