### ISSUE TITLE
Add `removeKnownProperty` method to ProfileInfo API

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/imperative#917]
* Update the type [here](https://github.com/zowe/imperative/blob/ca981d476b7a97fa6129de523c63e1a58000c139/packages/config/src/doc/IProfArgAttrs.ts#L31) to include undefined: `IProfArgValue | undefined`
* Add a `removeKnownProperty` method to the ProfileInfo class. The implementation should be simple - call `updateKnownProperty` with `value: undefined`.

> Regarding the `IProfArgValue` type, I think that adding an `undefined` is a good 'quick fix', but I'm wondering if it would be clear enough for others that setting the value to undefined will actually remove the property.

> In my opinion, introducing a method like `removeKnownProperty` is self-explanatory and it's implementation could be as simple as calling the `updateKnownProperty` method with value `undefined as any`.

_Originally posted by @juleskreutzer in https://github.com/zowe/zowe-cli/discussions/1561#discussioncomment-4105432_

**Comment by juleskreutzer** [comment]
@t1m0thyj Do you want me to open a PR for this?

**Comment by t1m0thyj** [comment]
> @t1m0thyj Do you want me to open a PR for this?

Sure, feel free to work on this issue 🙂
