### ISSUE TITLE
ProfileInfo wiki link unavailabe

### ISSUE THREAD

**Issue by sosadchuk** [zowe/imperative#933]
Hi,

[This chapter](https://github.com/zowe/imperative/wiki/Defining-and-Programming-Profiles#api-to-access-profiles-from-a-gui-app) in the wiki has a referece to the ProfileInfo class, however it leads to an unavailable location:
`https://wash.zowe.org:8443/job/Zowe%20CLI%20Bundle/job/next/zowe-nodejs-sdk-typedoc/classes/_zowe_imperative.profileinfo.html`
![image](https://user-images.githubusercontent.com/45584158/215800075-4630c90d-2ff2-4691-baf6-b45b5941a3fa.png)

I think it should point to the:
`https://docs.zowe.org/stable/typedoc/classes/_zowe_imperative.profileinfo.html`

Thanks,
Sergei.

**Comment by zFernand0** [comment]
Curious if we should try to address any other references of the old `wash.zowe.org` 
https://github.com/search?q=org%3Azowe+wash.zowe.org+&type=code
https://github.com/search?q=org%3Azowe+wash.zowe.org+&type=wikis

**Comment by t1m0thyj** [comment]
@sosadchuk Thanks for reporting this, the link should be fixed now.

@zFernand0 I don't see any other references to `wash.zowe.org` in CLI repos, so I think we should be good to close this.
