### ISSUE TITLE
Add `cause` property to ImperativeError

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/imperative#945]
Add a getter to the ImperativeError class that defines a `cause` property. It should return `this.mDetails` concatenated with `this.mAdditionalDetails`.

See MDN for details about the `cause` property on JS errors: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause

**Comment by LalitAswal** [comment]
#### can I work on this issue
#### if I am not wrong I just have to add
```ts
 /**
     * @type {string}
     * @memberof ImperativeError
     */
    public  get cause(): string {
    return `${this.mDetails} ${this.mAdditionalDetails}`;
  }
```
### in error/src/ImperativeError.ts file right?

**Comment by LalitAswal** [comment]
> @LalitAswal Sure, feel free to 🙂 I've assigned you to the issue.
> 
> I believe we'll want to separate them with a newline character: `` return `${this.mDetails}\n${this.mAdditionalDetails}`; ``
just have doubts about this.mAdditionalDetails ( this property is not defined, should i have to define it ?)
is it  this.additionalDetails

**Comment by t1m0thyj** [comment]
Good catch, `this.mDetails` is not a string and `this.mAdditionalDetails` is not defined. So I think what we really want is:
``return `${this.details}\n${this.additionalDetails}`;``

**Comment by LalitAswal** [comment]
> Good catch, `this.mDetails` is not a string and `this.mAdditionalDetails` is not defined. So I think what we really want is: `` return `${this.details}\n${this.additionalDetails}`; ``

thanks :)

**Comment by LalitAswal** [comment]
created PR please review it 😊

**Comment by t1m0thyj** [comment]
Closing this issue since it doesn't seem possible to override the `cause` property on JS errors.

Feel free to pick up any other issues labeled as [good first issue](https://github.com/zowe/imperative/labels/good%20first%20issue) 🙂
